
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: timesheets_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: timesheets_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  #encoding: utf8
  reconnect: false
  database: timesheets_production
  pool: 5
  username: thevirtu_root
  password: eshare
  host: localhost
  